id: I83958DF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:59:50+00:00'
last_modified: '2022-06-09T04:54:28.703966+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18898
  title: བོད་ལྗོངས་འཕེལ་རྒྱས་དང་ཡར་ཐོན་བྱུང་ཚུལ༎ ༼༢༠༡༣ལོའི་ཟླ༡༠པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '3822':
      image_group_id: I8LS18900
      title: Volume 1 of bod ljongs 'phel rgyas dang yar thon byung tshul// (2013lo'i
        zla10par/)
      total_pages: 72
      order: 1
      base_file: 3822.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
