id: opecha:P008158
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18898
  title: བོད་ལྗོངས་འཕེལ་རྒྱས་དང་ཡར་ཐོན་བྱུང་ཚུལ༎ ༼༢༠༡༣ལོའི་ཟླ༡༠པར།༽
  volume:
    25492bccbfe541b18fbcb86148b1910b:
      image_group_id: I8LS18900
      title: Volume 1 of bod ljongs 'phel rgyas dang yar thon byung tshul// (2013lo'i
        zla10par/)
      volume_number: 1
      total_pages: 72
  author: ''
ebook_metadata:
  title: བོད་ལྗོངས་འཕེལ་རྒྱས་དང་ཡར་ཐོན་བྱུང་ཚུལ༎ ༼༢༠༡༣ལོའི་ཟླ༡༠པར།༽
  author: ''
  sku: P008158
  cover: cover.jpg
  layers:
  - pagination
