id: P008158
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18898
  title: བོད་ལྗོངས་འཕེལ་རྒྱས་དང་ཡར་ཐོན་བྱུང་ཚུལ༎ ༼༢༠༡༣ལོའི་ཟླ༡༠པར།༽
  author: ''
  volumes:
    4285ff2e0f1d41dbb131e90e2a663e21:
      image_group_id: I8LS18900
      title: ''
      volume_number: 1
      total_pages: 72
ebook_metadata:
  title: བོད་ལྗོངས་འཕེལ་རྒྱས་དང་ཡར་ཐོན་བྱུང་ཚུལ༎ ༼༢༠༡༣ལོའི་ཟླ༡༠པར།༽
  author: ''
  sku: P008158
  cover: cover.jpg
  layers:
  - pagination
